#!/bin/bash
mkdir -p public/images/works/{civil,commercial,residential,industrial}
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/4/4b/Road_construction_in_Botswana.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/road.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/d/de/Concrete_bridge_construction_site_near_Reily%2C_Ohio_1909_%283199663235%29.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/bridge.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/0/0b/Concrete_Drainage_Sump_Beaminster_Tunnel_-_geograph.org.uk_-_4471668.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/drainage.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/e/e5/Digging_underground_pipe_instalation_water_drainage_roof_%284%29.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/water.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/5/57/Sewer_repairs_at_Appley%2C_Ryde%2C_Isle_of_Wight%2C_England.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/sewerage.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/4/4b/Utility_trench_in_Bwy_%40_42_St_jeh.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/utilities.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/2/21/Excavator_and_earthworks_by_Bluestone_-_geograph.org.uk_-_7512741.jpg?utm_source=en.wikipedia.org" -o public/images/works/civil/land.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/7/76/Construction_of_a_new_office-building_near_Beatrixkwartier_in_The_Hague_city%3B_high_resolution_image_by_FotoDutch%2C_June_2013.jpg?utm_source=en.wikipedia.org" -o public/images/works/commercial/office.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/1/1f/Jerusalem_Zion_Square_Shopping_mall_construction_site.JPG?utm_source=en.wikipedia.org" -o public/images/works/commercial/retail.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/7/7d/Construction_site%2C_Ivy_Lane_School%2C_Wakefield_-_geograph.org.uk_-_8062147.jpg?utm_source=en.wikipedia.org" -o public/images/works/commercial/institutional.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/a/ad/Balatonakali_house_under_construction.jpg?utm_source=en.wikipedia.org" -o public/images/works/residential/villa.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/9/9f/11_Liebherr_construction_crane_at_a_Strabag_company_construction_site_of_apartment_building_in_Budapest%2C_Hungary.jpg?utm_source=en.wikipedia.org" -o public/images/works/residential/apartment.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/9/96/Construction_site%2C_off_Vauxhall_Road_-_geograph.org.uk_-_6914215.jpg?utm_source=en.wikipedia.org" -o public/images/works/residential/gated.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/3/36/BubbleDeck_SemiPrecastPanel.jpg?utm_source=en.wikipedia.org" -o public/images/works/residential/renovation.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/9/9b/Steel_frame_to_new_warehouse_for_Next_-_geograph.org.uk_-_4477870.jpg?utm_source=en.wikipedia.org" -o public/images/works/industrial/warehouse.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/4/40/IIT_Mandi_South_Campus_under_construction_Dec_2012_DSC_0923e.jpg?utm_source=en.wikipedia.org" -o public/images/works/industrial/peb.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/4/46/Industrial_Plant_-_geograph.org.uk_-_4200955.jpg?utm_source=en.wikipedia.org" -o public/images/works/industrial/factory.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/d/dc/Les_Portes_d%27Arcueil%2C_construction_6.jpg?utm_source=en.wikipedia.org" -o public/images/works/industrial/cold.jpg
curl -sL -A "AntigravityBot/1.0" "https://upload.wikimedia.org/wikipedia/commons/f/f2/VIEW_NORTHEAST%2C_NORTH_ELEVATION_OF_WALL_7%2C_CONCRETE_SECTION_OF_STONE_RUBBLE_WALL_EAST_OF_MILL_FOUNDATION._-_Shenandoah_Pulp_Mill%2C_Shenandoah_Street%2C_Harpers_Ferry%2C_Jefferson_HAER_WVA%2C19-HARF%2C31-11.tif?utm_source=en.wikipedia.org" -o public/images/works/industrial/foundation.jpg
